tango_with_django_project/rango/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'rango'
urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('add_category/', views.add_category, name="add_category"),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name="add_page"),
    path('category/<slug:category_name_slug>/', views.show_category, name="show_category"),
    # path('register/', views.register, name="register"),
    # path('login/', views.user_login, name="login"),
    # path('logout/', views.user_logout, name="logout"),
    path('restricted/', views.restricted, name="restricted"),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from rango import views
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'


urlpatterns = [
    path('', views.index, name="index"),
    path('rango/', include('rango.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('accounts/register/', MyRegistrationView.as_view(), name="registration_register"),
    path('admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import  authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from datetime import datetime

# Create your views here.

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if(datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    pages_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': pages_list}

    visitor_cookie_handler(request)
    context_dict["visits"] = request.session["visits"]

    response = render(request, 'rango/index.html', context=context_dict)
    return response


def about(request):
    context_dict = {'yourname': "Michał Machnik"}

    visitor_cookie_handler(request)
    context_dict["visits"] = request.session["visits"]
    response = render(request, 'rango/about.html', context=context_dict)

    return response


def show_category(request, category_name_slug):
    context_dict ={}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict["pages"] = pages
        context_dict["category"] = category
    except Category.DoesNotExist:
        context_dict["pages"] = None
        context_dict["category"] = None

    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


'''def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', {'user_form': user_form,
                                                    'profile_form': profile_form,
                                                    'registered': registered})'''

'''def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return render(request, 'rango/login.html', {"error_message": "Your Rango account is disabled."})
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return render(request, 'rango/login.html', {"error_message": "Invalid login details supplied."})
    else:
        return render(request, 'rango/login.html', {})'''


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {"msg": "Since you're logged in, you can see this text!"})


'''@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))'''

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        ...here is the about page! <br/>
        This tutorial was created by <strong> {{ yourname }} </strong>. <br/>
    </div>
    <div>
        <p>Visits: {{ visits }}</p>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of cat">
    </div>
{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
    <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
    <h2 class="form-signin-heading"> Add a Category</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <br/>
        <button class="btn btn-primary" type="submit" name="submit">
            Add Category
        </button>
    </form>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Add Page
{% endblock %}

{% block body_block %}
    {% if category %}
        <form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
        <h2 class="form-signin-heading"> Add a Page to
            <a href="/rango/category/{{category.slug}}/">{{ category.name }}</a></h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br/>
            {{ field }}<br/>
        {% endfor %}
        <br/>
        <button class="btn btn-primary" type="submit" name="submit">
            Add Page
        </button>
        </form>
    {% else %}
        <p>This category does not exist.</p>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>

{% load static %}
{% load rango_template_tags %}

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>

    <body>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>

        <div>
            {% block body_block %}
            {% endblock %}  
        </div>
        <hr>
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'rango:login' %}">Sign In</a></li> 
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
            {% endif %}
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>      
            </ul>
        </div>
    </body>

</html>

tango_with_django_project/templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title> Rango - {% block title_block %}How to Tango with Django!{% endblock %} </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:about' %}">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:restricted' %}">Restricted Page</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
          {% block body_block %}
          {% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

<!--
<!DOCTYPE html>

{% load static %}
{% load rango_template_tags %}

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>

    <body>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>

        <div>
            {% block body_block %}
            {% endblock %}  
        </div>
        <hr>
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
            {% else %}
                <li><a href="{% url 'auth_login' %}">Sign In</a></li> 
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
            {% endif %}
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>      
            </ul>
        </div>
    </body>

</html>
-->

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
    {% if user.is_authenticated %}
        <br/><a href="{% url 'rango:add_page' category.slug %}">Add a New Page</a><br/>
    {% else %}
        <br/>You have to sign in to add a new pages.<br/>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/cats.html
<ul class="list-group">
{% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
            <li class="list-group-item"><strong><a href="{% url 'rango:show_category' c.slug %}"> {{ c.name }} </a></strong></li>
        {% else %}
            <li class="list-group-item"><a href="{% url 'rango:show_category' c.slug %}"> {{ c.name }} </a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no cateogries present.</strong></li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        <h1 class="display-3">Rango says...</h1>
        {% if user.is_authenticated %}
            ...hey there {{ user.username }}! <br/>
        {% else %}
            ...hey there partner! <br/>
        {% endif %}
    </div>

    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Most Liked Categories</h4>
            <p>
            {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}"> {{ category.name }} </a></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
            </p>
        </div>
        <div class="col-lg-6">
            <h4>Most Viewed Pages</h4>
            <p>
            {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                <li class="list-group-item"><a href="{{ page.url }}"> {{ page.title }} </a></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
            </p>
        </div>
    </div>
    <img class="img-fluid" src="{% static 'images/rango.jpg' %}" alt="Picture of Rango">
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block%}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50"><br>
        Password: <input type="password" name="password" value="" size="50"><br>
        <input type="submit" value="submit">
    </form>
    <div>
        {% if error_message %}
            {{ error_message }}
        {% endif %}
    </div>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends 'rango/base.html '%}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to homepage</a><br>
    {% else %}
        Rango says: <strong>register here!</strong><br>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register">
        </form>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    Restricted Area
{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        {{ msg }}
    {% else %}
        <strong>You must sign in to see content.</strong>
    {% endif %}
{% endblock %}